funding/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.ListView.as_view(), name='list'),
    url(r'add/$', views.CreateView.as_view(), name='add'),
    url(r'^(?P<pk>\d+)/vote/$', views.VoteView.as_view(), name='vote'),
]

lokanhomepage/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth.views import *
from django.contrib import admin

from . import views
admin.autodiscover()

urlpatterns = [
    # Authentication
    url(r'^login/', login, name='login'),
    url(r'^logout/', logout, name='logout'),
    url(r'^password_change/', password_change, name='password_change'),
    url(r'^password_change_done/', password_change_done,
        name='password_change_done'),
    # Apps
    url(r'^activities/', include('activities.urls', namespace='activities')),
    url(r'^members/', include('members.urls', namespace='members')),
    url(r'^funding/', include('funding.urls', namespace='funding')),
    url(r'^notifications/', include('notifications.urls', namespace='notifications')),
    # Other
    url(r'^admin/', include(admin.site.urls)),
    #url(r'^admin/defender/', include('defender.urls')),
    url(r'^about/', views.AboutView.as_view(), name='about'),
    url(r'^$', views.IndexView.as_view(), name='index'),
]

members/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^list/$', views.ListView.as_view(), name='list'),
]

members/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.conf import settings
from model_utils.models import TimeStampedModel

YEARS = (
        (2014, 2014),
        (2015, 2015),
        (2016, 2016),
    )


class Member(TimeStampedModel):

    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField(null=True, blank=True)
    user_profile = models.OneToOneField(settings.AUTH_USER_MODEL, null=True,
        blank=True)

    def boardmember_years(self):
        return Boardmember.objects.filter(
            member=self.id).values_list('year', flat=True)

    def get_absolute_url(self):
        return reverse('members:list')

    def __str__(self):
        return '{} {}'.format(self.first_name, self.last_name)


class Membership(TimeStampedModel):

    member = models.ForeignKey(Member)
    year = models.SmallIntegerField(choices=YEARS)

    def __str__(self):
        return '{} {}'.format(self.member, self.year)

    class Meta():
        unique_together = ("member", "year")


class Boardmember(TimeStampedModel):

    TITLES = (
        ('Ordförande', 'Ordförande'),
        ('Kassör', 'Kassör'),
        ('Sekreterare', 'Sekreterare'),
        ('Ledamot', 'Ledamot'),
    )
    member = models.ForeignKey(Member)
    year = models.SmallIntegerField(choices=YEARS)
    title = models.CharField(max_length=15, choices=TITLES)

    def __str__(self):
        return '{} {} {}'.format(self.title, self.member, self.year)

    class Meta():
        unique_together = ("member", "year")

members/views.py
from django.views.generic import ListView, TemplateView
from django.conf import settings
from .models import Member
from braces.views import LoginRequiredMixin


class IndexView(TemplateView):
    template_name = 'members/member_index.html'


class ListView(LoginRequiredMixin, ListView):
    model = Member

    def get_queryset(self):
        return Member.objects.filter(
            membership__year=settings.BUSINESS_YEAR).order_by('last_name')

members/templates/members/member_index.html
{% extends "base.html" %}
{% load static from staticfiles %}

{% block body_title %}Bli medlem i Lokan!{% endblock %}

{% block base_body %}
<div class="small-6 small-centered columns">

Medlemsavgiften för {{ settings.BUSINESS_YEAR }} är <strong>{{ settings.MEMBERSHIP_FEE }} kr</strong> och sätts in på:<br>

<strong>PG 304109-2</strong><br>

Glöm inte att skriva ditt namn och "Medlemsavgift {{ settings.BUSINESS_YEAR }}".

<hr>
<ul class="pricing-table">
  <li class="title">Medlemskap {{ settings.BUSINESS_YEAR }}</li>
  <li class="price">{{ settings.MEMBERSHIP_FEE }} kr</li>
  <li class="description">Vad väntar du på?</li>
  <li class="bullet-item">Sök projektbidrag</li>
  <li class="bullet-item">Var med på roliga aktiviteter</li>
  <li class="bullet-item">Full tillgång till hemsidan</li>
  <li class="cta-button"><a class="button" href="">Bli medlem nu!</a></li>
</ul>

</div>
{% endblock %}

members/templates/members/member_list.html
{% extends "base.html" %}

{% block body_title %}Lista över medlemmar {{ settings.BUSINESS_YEAR }}{% endblock %}

{% block base_body %}
<p>
<table class="small-6 small-centered columns">
  <thead>
    <tr>
     <th>Namn</th>
     <th>Styrelseposition</th>
    </tr>
  </thead>
  <tbody>
{% for member in member_list %}
    <tr>
      <td>{{ member }}</td>
      <td>{% if member.boardmember_set.all.0.title %} {{ member.boardmember_set.all.0.title }}{% else %}-{% endif %}</td>
    </tr>
{% endfor %}
  </tbody>
</table>

<p class="text-center">
Totalt antal medlemmar: {{ member_list|length }}
</p>
{% endblock base_body %}