activities/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.ListUpcomingView.as_view(), name='upcominglist'),
    url(r'^old/$', views.ListOldView.as_view(), name='oldlist'),
    url(r'^add/$', views.CreateView.as_view(), name='add'),
    url(r'^edit/(?P<pk>\d+)/$', views.UpdateView.as_view(), name='edit'),
]

funding/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.ListView.as_view(), name='list'),
    url(r'add/$', views.CreateView.as_view(), name='add'),
    url(r'^(?P<pk>\d+)/vote/$', views.VoteView.as_view(), name='vote'),
]

lokanhomepage/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth.views import *
from django.contrib import admin

from . import views
admin.autodiscover()

urlpatterns = [
    # Authentication
    url(r'^login/', login, name='login'),
    url(r'^logout/', logout, name='logout'),
    url(r'^password_change/', password_change, name='password_change'),
    url(r'^password_change_done/', password_change_done,
        name='password_change_done'),
    # Apps
    url(r'^activities/', include('activities.urls', namespace='activities')),
    url(r'^members/', include('members.urls', namespace='members')),
    url(r'^funding/', include('funding.urls', namespace='funding')),
    url(r'^notifications/', include('notifications.urls', namespace='notifications')),
    # Other
    url(r'^admin/', include(admin.site.urls)),
    #url(r'^admin/defender/', include('defender.urls')),
    url(r'^about/', views.AboutView.as_view(), name='about'),
    url(r'^$', views.IndexView.as_view(), name='index'),
]

activities/models.py
from django.db import models
from django.contrib.auth.models import User
from model_utils.models import TimeStampedModel


class Activity(TimeStampedModel):
    created_by = models.ForeignKey(User, verbose_name="Arrangör")
    datetime = models.DateTimeField("Datum/Tid")
    activity = models.CharField("Aktivitet", max_length=30)
    place = models.CharField("Plats", max_length=30)
    notes = models.TextField("Extra info")

    def __str__(self):
        return '{} {}'.format(self.activity, self.datetime)

activities/views.py
from django.core.urlresolvers import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView
from django.utils import timezone

from .models import Activity
from notifications.tasks import notify
from braces.views import LoginRequiredMixin


class ListUpcomingView(ListView):
    model = Activity

    def get_queryset(self):
        return Activity.objects.filter(
        datetime__gte=timezone.now()).order_by('datetime')

    def get_context_data(self, **kwargs):
        context = super(ListUpcomingView, self).get_context_data(**kwargs)
        context['upcoming'] = True
        return context


class ListOldView(ListView):
    model = Activity

    def get_queryset(self):
        return Activity.objects.filter(
        datetime__lte=timezone.now()).order_by('-datetime')


class CreateView(LoginRequiredMixin, CreateView):
    model = Activity
    fields = ['datetime', 'place', 'activity', 'notes']
    success_url = reverse_lazy('activities:upcominglist')

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        notify.delay('activities')
        return super(CreateView, self).form_valid(form)


class UpdateView(LoginRequiredMixin, UpdateView):
    model = Activity
    fields = ['created_by', 'datetime', 'activity', 'place', 'notes']
    success_url = reverse_lazy('activities:upcominglist')

activities/templates/activities/activity_form.html
{% extends "base.html" %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'jquery.datetimepicker.css' %}"/>
{% endblock css %}

{% block body_title %}
 {% if activity.id %}Uppdatera{% else %}Skapa{% endif %} aktivitet
{% endblock body_title %}

{% block base_body %}
 <div class="small-6 small-centered columns">
  <form action="" method="post">
  {% csrf_token %}
  {{ form }}
  <input type="submit" value="{% if activity.id %}Uppdatera{% else %}Skapa{% endif %}" class="button expand"/>
  </form>
 </div>
{% endblock base_body %}


{% block body_js %}
<script src="{% static 'jquery.datetimepicker.js' %}"></script>

<script type="text/javascript">
  $(function() {
    $(" #id_datetime ").datetimepicker({format:"Y-m-d H:i",lang:"sv", dayOfWeekStart:1});
  });
</script>

{% endblock body_js %}

activities/templates/activities/activity_list.html
{% extends "base.html" %}

{% block body_title %}
Lista över {% if upcoming %}kommande{% else %}gamla{% endif %} aktiviteter {{ settings.BUSINESS_YEAR }}
{% endblock body_title%}

{% block base_body %}
<p>
<table class="small-12 small-centered columns">
  <thead>
    <tr>
     <th>När</th>
     {% if upcoming %}<th>Tid kvar</th>{% endif %}
     <th>Vad</th>
     <th>Var</th>
     <th>Hur</th>
     <th>Arrangör</th>
     {% if upcoming %}<th>Administrera</th>{% endif %}
    </tr>
  </thead>
  <tbody>
{% for activity in activity_list %}
    <tr>
      <td>{{ activity.datetime|date:"D j F"|capfirst }},
      kl. {{ activity.datetime|time:"H:i" }}</td>
      {% if upcoming %}<td>{{ activity.datetime|timeuntil }}</td>{% endif %}
      <td>{{ activity.activity }}</td>
      <td>{{ activity.place }}</td>
      <td>{{ activity.notes }}</td>
      <td>{{ activity.created_by }}</td>
      {% if upcoming %}
       <td>{% if user == activity.created_by %}
       <a href="{% url 'activities:edit' activity.id %}">
       <span class="label">Ändra</span></a>
       {% endif %}
       </td>
      {% endif %}
    </tr>
{% endfor %}
  </tbody>
</table>

{% endblock base_body %}