funding/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.ListView.as_view(), name='list'),
    url(r'add/$', views.CreateView.as_view(), name='add'),
    url(r'^(?P<pk>\d+)/vote/$', views.VoteView.as_view(), name='vote'),
]

lokanhomepage/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth.views import *
from django.contrib import admin

from . import views
admin.autodiscover()

urlpatterns = [
    # Authentication
    url(r'^login/', login, name='login'),
    url(r'^logout/', logout, name='logout'),
    url(r'^password_change/', password_change, name='password_change'),
    url(r'^password_change_done/', password_change_done,
        name='password_change_done'),
    # Apps
    url(r'^activities/', include('activities.urls', namespace='activities')),
    url(r'^members/', include('members.urls', namespace='members')),
    url(r'^funding/', include('funding.urls', namespace='funding')),
    url(r'^notifications/', include('notifications.urls', namespace='notifications')),
    # Other
    url(r'^admin/', include(admin.site.urls)),
    #url(r'^admin/defender/', include('defender.urls')),
    url(r'^about/', views.AboutView.as_view(), name='about'),
    url(r'^$', views.IndexView.as_view(), name='index'),
]

funding/models.py
from django.core.urlresolvers import reverse
from django.db import models
from django.contrib.auth.models import User
from members.models import Member
from model_utils.models import TimeStampedModel


class Project(TimeStampedModel):

    created_by = models.ForeignKey(User)
    applier = models.ForeignKey(Member, verbose_name="Ansökare")
    title = models.CharField("Titel", max_length=50)
    description = models.TextField("Beskrivning")
    amount = models.IntegerField("Önskad summa")
    year = models.SmallIntegerField("Verksamhetsår", null=True)

    def positive_votes(self):
        return Vote.objects.filter(project=self.id, positive=True).count()

    def negative_votes(self):
        return Vote.objects.filter(project=self.id, positive=False).count()

    def is_approved(self):
        return self.positive_votes() >= 3

    def is_denied(self):
        return self.negative_votes() >= 3

    def has_voted(self):
        return Vote.objects.filter(
            project=self.id).values_list('user', flat=True)

    def get_absolute_url(self):
        return reverse('funding:list')

    def __str__(self):
        return '{}'.format(self.title)


class Vote(TimeStampedModel):
    project = models.ForeignKey(Project)
    user = models.ForeignKey(User)
    positive = models.BooleanField(default=False)

    class Meta():
        unique_together = ("project", "user")

    def get_absolute_url(self):
        return reverse('funding:list')

    def __str__(self):
        return '{} {} {}'.format(self.project, self.user, self.positive)

funding/forms.py
from django import forms
from .models import Vote


class VoteForm(forms.ModelForm):
    BOOLEAN_CHOICES = (('1', 'Ja'), ('0', 'Nej'))
    positive = forms.ChoiceField(choices=BOOLEAN_CHOICES,
                                 widget=forms.RadioSelect)

    class Meta:
        model = Vote
        exclude = ()
        #fields = ['positive']

funding/views.py
from django.views.generic import ListView, CreateView
from django.conf import settings
from django.contrib.auth.mixins import PermissionRequiredMixin
from .models import Project, Vote
from braces.views import LoginRequiredMixin
from lokanhomepage.mixins import MayVoteMixin
from notifications.tasks import notify
from .forms import VoteForm
from members.models import Member


class ListView(LoginRequiredMixin, ListView):
    model = Project


class CreateView(LoginRequiredMixin, CreateView):
    model = Project
    fields = ['applier', 'amount', 'title', 'description']

    def get_initial(self):
        initial = super(CreateView, self).get_initial()
        try:
            initial['applier'] = Member.objects.get(
                user_profile=self.request.user)
        except:
            pass
        return initial

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        form.instance.year = settings.BUSINESS_YEAR
        notify.delay('funding')
        return super(CreateView, self).form_valid(form)


class VoteView(PermissionRequiredMixin, CreateView):
    model = Vote
    form_class = VoteForm
    permission_required = 'funding.can_vote'

    def get_context_data(self, **kwargs):
        context = super(VoteView, self).get_context_data(**kwargs)
        context['project'] = Project.objects.get(pk=self.kwargs['pk'])
        return context

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.project = Project.objects.get(pk=self.kwargs['pk'])
        return super(VoteView, self).form_valid(form)

funding/templates/funding/project_form.html
{% extends "base.html" %}

{% block body_title %}Ansökan om projektbidrag{% endblock body_title %}

{% block base_body %}
 <div class="small-6 small-centered columns">
<form action="" method="post">{% csrf_token %}
    {{ form }}
    <hr>OBS! Du måste kunna styrka utgifterna med kvitto!<hr>
    <input type="submit" value="Ansök"  class="button expand"/>
</form>
</div>
{% endblock base_body %}

funding/templates/funding/project_list.html
{% extends "base.html" %}

{% block body_title %}Lista över projektbidragsansökningar{% endblock body_title%}

{% block base_body %}

<p>
<table class="small-12 small-centered columns">
  <thead>
    <tr>
     <th>Ansökare</th>
     <th>Titel</th>
     <th>Beskrivning</th>
     <th>Summa</th>
     <th>Verksamhetsår</th>
     <th>Röster</th>
    </tr>
  </thead>
  <tbody>
{% for project in project_list %}
    <tr>
      <td>{{ project.applier }}</td>
      <td>{{ project.title }}</td>
      <td>{{ project.description }}</td>
      <td>{{ project.amount }}</td>
      <td>{{ project.year }}</td>
      <td>
      {% if project.is_approved %}<span class="success label">Godkänd!</span>
      {% elif project.is_denied %}<span class="alert label">Nedröstad</span>
      {% elif user.id not in project.has_voted and project.year in user.member.boardmember_years %}
      <a href="{% url 'funding:vote' project.id %}">
      <span class="label">Rösta</span></a>
      {% else %}
      <div class="progress success">
       {% if project.positive_votes == 1 %}
       <span class="meter" style="width: 33%"><div align="center">1/3</div></span>
       {% elif project.positive_votes == 2 %}
       <span class="meter" style="width: 66%"><div align="center">2/3</div></span>
       {% else %}
       <span class="meter" style="width: 0%">0/3</span>
       {% endif %}
      </div>
      <div class="progress alert">
       {% if project.negative_votes == 1 %}
       <span class="meter" style="width: 33%"><div align="center">1/3</div></span>
       {% elif project.negative_votes == 2 %}
       <span class="meter" style="width: 66%"><div align="center">2/3</div></span>
       {% else %}
       <span class="meter" style="width: 0%">0/3</span>
       {% endif %}
      </div>

      {% endif %}
      </td>
    </tr>
{% endfor %}
  </tbody>
</table>

{% endblock base_body %}

funding/templates/funding/vote_form.html
{% extends "base.html" %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'jquery-ui.min.css' %}"/>
{% endblock css %}

{% block body_title %}Rösta för projekt "{{ project.title }}"{% endblock %}

{% block base_body %}
<div class="small-6 small-centered columns">

<p>
<strong>Ansökare:</strong> {{ project.applier }}<br>
<strong>Titel:</strong> {{ project.title }}<br>
<strong>Beskrivning:</strong> {{ project.description }}<br>
<strong>Summa:</strong> {{ project.amount }}<br>
<strong>Verksamhetsår:</strong> {{ project.year }}
</p>

<hr>

<form action="" method="post">{% csrf_token %}
<div id="radioset">
{% for choice in form.positive.field.choices %}

    <input type="radio" name="positive" value="{{choice.0}}" id="radio{{choice.0}}"/>
    <label for="radio{{choice.0}}">{{choice.1}}</label>

{% endfor %}
</div><hr>
<input type="submit" value="Rösta" class="button expand"/>
</form>

</div>
{% endblock base_body %}

{% block body_js %}
<script src="{% static 'jquery-ui.min.js' %}"></script>

<script>
$( "#radioset" ).buttonset();
</script>

{% endblock body_js %}